# Generated by Django 2.1 on 2018-08-13 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edc_reference', '0004_auto_20180116_1528'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='reference',
            name='edc_referen_identif_351847_idx',
        ),
        migrations.RemoveIndex(
            model_name='reference',
            name='edc_referen_report__69deaa_idx',
        ),
        migrations.AlterIndexTogether(
            name='reference',
            index_together=set(),
        ),
    ]
