# Generated by Django 2.1 on 2018-08-17 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edc_reference', '0004_auto_20180116_1528'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='reference',
            name='edc_reference_reference_identifier_timepoint_repo_526121ab_idx',
        ),
    ]
